config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users

  resources :links do
  	resources :votes
  	resources :comments
  end

  root 'links#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :link
  validates :body, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
	validates :title, presence: true
	validates :url, presence: true
	belongs_to :user
	has_many :votes
	has_many :comments

	def upvote(user)
		@vote = votes.new(vote_value: 1, user: user)
		@vote.save
	end 

	def downvote(user)
		@vote = votes.new(vote_value: -1, user: user)
		@vote.save
	end

	def upvotes
		votes.where(vote_value: 1).count
	end

	def downvotes
		votes.where(vote_value: -1).count
	end

	def total_score
		votes.sum(:vote_value)
	end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true
  has_many :links
  has_many :votes
  has_many :comments
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :user
	belongs_to :link
	validates_inclusion_of :vote_value, in: [-1,1]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @link, notice: 'Comment was successfully created.' }
        format.js { }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @link = @comment.link
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @link, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @Vote = Vote.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @vote = current_user.votes.new(link_params)
    respond_to do |format|
      if @vote.save
        format.js   {
          if @vote.vote_value == 1
            @new_value = @vote.link.upvotes
            @id_name = "#upvotes-" + @vote.link.id.to_s
          else
            @new_value = @vote.link.downvotes
            @id_name = "#downvotes-" + @vote.link.id.to_s
          end          

         }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @vote.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:vote).permit(:user_id, :link_id, :vote_value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
	<div class="comments_wrapper clearfix">
		<div class="pull-left">
			<p class="lead"><%= comment.body %></p>
			<p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by <%= comment.user.email %></small></p>
		</div>

		<div class="btn-group pull-right">
			<% if comment.user == current_user -%>
				<%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-secondary" %>
			<% end %>
		</div>
	</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :link_id %>
    <%= form.number_field :link_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
console.log("create.js.erb file - comments");

$("#comments").html("<%= escape_javascript(render :partial => @link.comments) %>");

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Raddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
<% end %>
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
	<a class="navbar-brand" href="\">Reddit Clone</a>
	<div class="collapse navbar-collapse" id="navbarCollapse">

<% if user_signed_in? %>

		<ul class="navbar-nav mr-auto">
			<li class="nav-item active"><%= link_to 'Submit Link', new_link_path, class: "nav-link" %></li>
			<li class="nav-item active"><%= link_to 'Account', edit_user_registration_path, class: "nav-link"  %></li>
			<li class="nav-item active"><%= link_to 'Sign out', destroy_user_session_path, :method => :delete, class: "nav-link"  %></li>
		</ul>
<% else %>
	<ul class="navbar-nav mr-auto">
		<li class="nav-item active"><%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %></li>
		<li class="nav-item active"><%= link_to 'Sign in', new_user_session_path, class: "nav-link" %></li>
	</ul>
<% end %>
</div>
</nav>

<div id="main_content" class="container">
	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: 'alert alert-info') %>
	<% end %>
	<div id="content" class="col-md-9 center-block">
		<%= yield %>
	</div>
</div>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<% @links.each do |link| %>
    <div class="link row clearfix">
      <h2>
        <%= link_to link.title, link %>
        <small class="author">Submitted <%= time_ago_in_words(link.created_at) %> ago 
          by <%= link.user.email %></small>
      </h2>

    </div>
    
    <div class="btn-group" role="group"  aria-label="Links">
      <%= link_to "Visit Link", link.url, class: "btn btn-secondary btn-sm" %>

      <%= form_for [link, Vote.new], :remote => true do |f| %>
        <%= f.hidden_field :link_id, :value => link.id %>        
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.hidden_field :vote_value, :value => "1" %>
        <%= button_tag(class: "btn btn-secondary btn-sm", id: "upvoter-#{link.id}") do %>
         <span class="fa fa-chevron-up"></span>
         Upvote
         <%= content_tag(:span, link.upvotes(), id: "upvotes-#{link.id}") %>
        <% end %>      

      <% end %>
      
      <%= form_for [link, Vote.new], :remote => true do |f| %>
        <%= f.hidden_field :link_id, :value => link.id %>        
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.hidden_field :vote_value, :value => "-1" %>

        <%= button_tag(class: "btn btn-secondary btn-sm", id: "downvoter-#{link.id}") do %>
         <span class="fa fa-chevron-down"></span>
         Downvote
         <%= content_tag(:span, link.downvotes(), id: "downvotes-#{link.id}") %>         
        <% end %>
      <% end %>
    
    </div>

<% end %>


<br>
<div class="btn-group mt-3" role="group" aria-label="New link">
  <%= link_to 'New Link', new_link_path, class: "btn btn-primary btn-md" %>
</div>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<div class="page-header">
  <h1><a href="<%= @link.url %>"><%= @link.title %></a><br> <small>Submitted by <%= @link.user.username %></small></h1>
</div>

<div class="btn-group">
	<%= link_to 'Visit URL', @link.url, class: "btn btn-primary" %>
</div>

<div class="btn-group pull-right">
      <%= form_for [@link, Vote.new], :remote => true do |f| %>
        <%= f.hidden_field :link_id, :value => @link.id %>        
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.hidden_field :vote_value, :value => "1" %>
        <%= button_tag(class: "btn btn-secondary btn-sm", id: "upvoter-#{@link.id}") do %>
         <span class="fa fa-chevron-up"></span>
         Upvote
         <%= content_tag(:span, @link.upvotes(), id: "upvotes-#{@link.id}") %>
        <% end %>      

      <% end %>
      
      <%= form_for [@link, Vote.new], :remote => true do |f| %>
        <%= f.hidden_field :link_id, :value => @link.id %>        
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.hidden_field :vote_value, :value => "-1" %>

        <%= button_tag(class: "btn btn-secondary btn-sm", id: "downvoter-#{@link.id}") do %>
         <span class="fa fa-chevron-down"></span>
         Downvote
         <%= content_tag(:span, @link.downvotes(), id: "downvotes-#{@link.id}") %>         
        <% end %>
      <% end %>
      </div>
      <% if @link.user == current_user -%>
      <div class="btn-group">
      	<%= link_to 'Edit', edit_link_path(@link), class: "btn btn-secondary" %>
      	<%= link_to 'Destroy', @link, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-secondary" %>
      </div>
      <% end -%>
      <h3 class="comments_title">
      	<%= @link.comments.count %> Comment(s)
      </h3>
      <div id="comments">
      	<%= render :partial => @link.comments %>
      </div>
      <%= simple_form_for [@link, Comment.new], remote: true do |f| %>
      <div class="field">
      	<%= f.text_area :body, class: "form-control" %>
      </div>
      <br>
      <%= f.submit "Add Comment", class: "btn btn-primary" %>
      <% end %>


<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/votes/create.js.erb
console.log("create.js.erb file");

$("<%= j @id_name %>").html("<%= j @new_value.to_s %>");